name: example
description: An example application for the defaultable package.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # The API package
  defaultable:
    path: ../defaultable

dev_dependencies:
  # The generator packages
  build_runner: ^2.4.11
  defaultable_generator:
    path: ../defaultable_generator

  lints: ^3.0.0