builders:
  defaultable:
    import: "package:defaultable_generator/builder.dart"
    builder_factories: ["defaultableBuilder"]
    build_extensions: {".dart": [".defaultable.g.dart"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]