name: defaultable_generator
description: The generator for the defaultable package.
version: 1.0.0
repository: https://github.com/leeflix/defaultable

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  defaultable: ^1.0.0

  build: ^3.0.0
  source_gen: ^3.0.0
  analyzer: 7.4.0
  recase: ^4.1.0

dev_dependencies:
  test: ^1.24.0