name: defaultable_generator
description: The generator for the defaultable package.
version: 1.0.3
repository: https://github.com/leeflix/defaultable

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  defaultable: ^1.0.0

  build: ^3.0.0
  source_gen: 3.0.0
  analyzer: ^7.4.0
  recase: ^4.1.0

#  collection: ^1.19.1
#  uuid: ^4.5.1
#  meta: ^1.16.0
#  dart_jsonwebtoken: ^3.2.0
#  dio: ^5.4.1
#  shelf: ^1.4.1
#  decimal: ^3.2.4
#  rational: ^2.2.3
#  freezed_annotation: ^3.1.0
#  json_annotation: ^4.9.0
#  auto_exporter_annotation: ^1.0.3

#dev_dependencies:
#  build_runner: ^2.6.0
#  build_test: ^3.0.0
#  freezed: ^3.2.0
#  json_serializable: ^6.10.0
#  auto_exporter: ^4.0.0