name: defaultable
description: Provides annotations for generating default instances of classes.
version: 0.1.0
publish_to: none # Prevents accidental publishing

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.12.0