name: defaultable
description: Provides annotations for generating default instances of classes.
version: 1.0.0
repository: https://github.com/leeflix/defaultable

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.12.0